//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintanenceOrder
    {
        public int OrderID { get; set; }
        public int ApartmentID { get; set; }
        public int UserID { get; set; }
        public string ProblemLocation { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<bool> ManagerApproval { get; set; }
        public Nullable<bool> MaintanenceVisit { get; set; }
        public Nullable<bool> MaintanenceCompletion { get; set; }
        public Nullable<int> UserFeedbackStar { get; set; }
        public string UserFeedback { get; set; }
    }
}
