//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public System.Guid UserID { get; set; }
        [Required]
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> UserApartmentID { get; set; }
        public string UserRoom { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
